---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agilizeerpcom/erpmacro.agilizeerp.com.br
    - /bin/cp -auvR app $DEPLOYPATH
    - /bin/cp -auvR bootstrap $DEPLOYPATH
    - /bin/cp -auvR config $DEPLOYPATH
    - /bin/cp -auvR database $DEPLOYPATH
    - /bin/cp -auvR public $DEPLOYPATH
    - /bin/cp -auvR resources $DEPLOYPATH
    - /bin/cp -auvR routes $DEPLOYPATH
    - /bin/cp -auv .htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -auv artisan $DEPLOYPATH/artisan
    - /bin/cp -auv bd.sql $DEPLOYPATH/bd.sql
    - /bin/cp -auv composer.json $DEPLOYPATH/composer.json
    - /bin/cp -auv comand_api.sql $DEPLOYPATH/comand_api.sql
    - /bin/cp -auv new_tables_api.sql $DEPLOYPATH/new_tables_api.sql
    - cd $DEPLOYPATH && php artisan migrate
    # - cd $DEPLOYPATH && php artisan cache:clear
    # - cd $DEPLOYPATH && php artisan config:clear
    # - cd $DEPLOYPATH && php artisan config:cache
    # - cd $DEPLOYPATH && php artisan route:cache
    # - cd $DEPLOYPATH && php composer.phar dump-autoload
