---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agilizeerpcom/erpmacro.agilizeerp.com.br
    - /bin/cp -auvR app $DEPLOYPATH/app
    - /bin/cp -auvR bootstrap $DEPLOYPATH/bootstrap
    - /bin/cp -auvR config $DEPLOYPATH/config
    - /bin/cp -auvR database $DEPLOYPATH/database
    - /bin/cp -auvR public $DEPLOYPATH/public
    - /bin/cp -auvR resources $DEPLOYPATH/resources
    - /bin/cp -auvR routes $DEPLOYPATH/routes
    - /bin/cp -auvR storage $DEPLOYPATH/storage
    - /bin/cp -auvR .env $DEPLOYPATH/.env
    - /bin/cp -auvR .htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -auvR artisan $DEPLOYPATH/artisan
    - /bin/cp -auvR bd.sql $DEPLOYPATH/bd.sql