---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agilizeerpcom/erpmacro.agilizeerp.com.br
    - /bin/cp -auvR app $DEPLOYPATH
    - /bin/cp -auvR bootstrap $DEPLOYPATH
    - /bin/cp -auvR config $DEPLOYPATH
    - /bin/cp -auvR database $DEPLOYPATH
    - /bin/cp -auvR public $DEPLOYPATH
    - /bin/cp -auvR resources $DEPLOYPATH
    - /bin/cp -auvR routes $DEPLOYPATH
    - /bin/cp -auvR storage $DEPLOYPATH
    - /bin/cp -auvR .env $DEPLOYPATH
    - /bin/cp -auvR .htaccess $DEPLOYPATH
    - /bin/cp -auvR artisan $DEPLOYPATH
    - /bin/cp -auvR bd.sql $DEPLOYPATH