---
deployment:
  tasks:
    - export DEPLOYPATH=/home/agilizeerpcom/erpmacro.agilizeerp.com.br
    - /bin/cp -auvR app $DEPLOYPATH
    - /bin/cp -auvR bootstrap $DEPLOYPATH
    - /bin/cp -auvR config $DEPLOYPATH
    - /bin/cp -auvR database $DEPLOYPATH
    - /bin/cp -auvR public $DEPLOYPATH
    - /bin/cp -auvR resources $DEPLOYPATH
    - /bin/cp -auvR routes $DEPLOYPATH
    - /bin/cp -auv .htaccess $DEPLOYPATH/.htaccess
    - /bin/cp -auv artisan $DEPLOYPATH/artisan
    - /bin/cp -auv bd.sql $DEPLOYPATH/bd.sql
    - /bin/php $DEPLOYPATH/artisan migrate